/**
 * Integration tests: execute the SQL generated by the command planners
 * against a real DuckDB database holding the acceptance fixture, through
 * the read-only SQL API (DbDataSource.runReadOnlySql) and the command
 * executor. Asserts numeric outputs and ordering, not just shapes.
 */
import * as reltab from "reltab";
import {
  DbDataSource,
  DuckDBDialect,
  FilterExp,
  tableQuery,
} from "reltab";
import "reltab-duckdb"; // side effect: registers the duckdb provider
import * as reltabDuckDB from "reltab-duckdb";
import { Expr } from "../src/stataCommand/ast";
import {
  CommandExecutionContext,
  executeCommand,
  GridUpdate,
} from "../src/stataCommand/executor";
import stataReference from "./fixtures/stataCrossValidation.json";

let dbds: DbDataSource;
let ctx: CommandExecutionContext;
let fullSchema: reltab.Schema;
let lastGrid: GridUpdate | null = null;

/**
 * The acceptance fixture:
 * - numeric columns a, b, c (a and b contain nulls)
 * - string column s with embedded single/double quotes and a null
 * - columns needing SQL identifier quoting: "has space", "select",
 *   "quote""name"
 * - date column d and timestamp column ts, each with a null
 */
const FIXTURE_DDL = `
CREATE TABLE stata_fixture (
  a INTEGER,
  b DOUBLE,
  c INTEGER,
  s VARCHAR,
  "has space" INTEGER,
  "select" VARCHAR,
  "quote""name" VARCHAR,
  d DATE,
  ts TIMESTAMP
)`;

const FIXTURE_ROWS = `
INSERT INTO stata_fixture VALUES
  (1,    1.5,  1, 'alpha',     10,   'x', 'q1', DATE '2026-01-01', TIMESTAMP '2026-01-01 08:00:00'),
  (2,    2.5,  2, 'it''s',     20,   'x', 'q1', DATE '2026-01-02', TIMESTAMP '2026-01-02 09:30:00'),
  (3,    NULL, 3, 'say "hi"',  30,   'y', 'q2', DATE '2026-01-03', TIMESTAMP '2026-01-03 10:00:00'),
  (4,    4.5,  3, NULL,        40,   'y', NULL, NULL,              NULL),
  (NULL, 5.5,  5, 'gamma',     50,   'y', 'q2', DATE '2026-02-01', TIMESTAMP '2026-02-01 12:15:30'),
  (6,    6.5,  5, 'alpha',     NULL, 'z', 'q3', DATE '2026-03-01', TIMESTAMP '2026-03-01 23:59:59')`;

beforeAll(async () => {
  const conn = await reltab.getConnection({
    providerName: "duckdb",
    resourceId: ":memory:",
  });
  dbds = conn as DbDataSource;
  const driver = dbds.db as reltabDuckDB.DuckDBDriver;
  await driver.runSqlQuery(FIXTURE_DDL);
  await driver.runSqlQuery(FIXTURE_ROWS);

  fullSchema = await dbds.getTableSchema("stata_fixture");
  ctx = {
    schema: fullSchema,
    dialect: DuckDBDialect,
    baseQuery: tableQuery("stata_fixture"),
    sortKey: [],
    sessionFilter: null,
    runReadOnlySql: (sql: string) => dbds.runReadOnlySql(sql),
    applyGrid: (update) => {
      lastGrid = update;
    },
  };
});

beforeEach(() => {
  lastGrid = null;
  ctx.schema = fullSchema;
  ctx.sortKey = [];
  ctx.sessionFilter = null;
});

describe("read-only SQL guard", () => {
  test("rejects mutation statements", async () => {
    await expect(
      dbds.runReadOnlySql("DELETE FROM stata_fixture")
    ).rejects.toThrow("only a single read-only SELECT");
    await expect(
      dbds.runReadOnlySql("INSERT INTO stata_fixture VALUES (1)")
    ).rejects.toThrow("only a single read-only SELECT");
    await expect(dbds.runReadOnlySql("PRAGMA database_list")).rejects.toThrow(
      "only a single read-only SELECT"
    );
  });

  test("rejects multiple statements and comments", async () => {
    await expect(
      dbds.runReadOnlySql("SELECT 1; SELECT 2")
    ).rejects.toThrow("only a single SQL statement");
    await expect(
      dbds.runReadOnlySql("SELECT 1 -- sneaky")
    ).rejects.toThrow("comments are not permitted");
  });

  test("allows trailing semicolon and quoted semicolons", async () => {
    const r1 = await dbds.runReadOnlySql("SELECT 1 AS x;");
    expect(r1.rows).toEqual([{ x: 1 }]);
    const r2 = await dbds.runReadOnlySql("SELECT 'a;b' AS x");
    expect(r2.rows).toEqual([{ x: "a;b" }]);
  });

  test("normalizes bigint and returns schema", async () => {
    const r = await dbds.runReadOnlySql(
      "SELECT count(*) AS n FROM stata_fixture"
    );
    expect(r.rows).toEqual([{ n: 6 }]);
    expect(typeof r.rows[0].n).toBe("number");
    expect(r.schema.columns).toEqual(["n"]);
  });
});

describe("summarize", () => {
  test("sum a b if c > 2 returns exact statistics per variable", async () => {
    const outcome = await executeCommand("sum a b if c > 2", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.sql).toContain("stddev_samp");
    const block = outcome.blocks[0];
    expect(block.kind).toBe("table");
    if (block.kind !== "table") return;
    expect(block.columns).toEqual([
      "Variable",
      "N",
      "Mean",
      "Std. dev.",
      "Min",
      "Max",
    ]);
    expect(block.rows.length).toBe(2);

    // rows where c > 2: a in {3, 4, NULL, 6}, b in {NULL, 4.5, 5.5, 6.5}
    const [aRow, bRow] = block.rows;
    expect(aRow[0]).toBe("a");
    expect(aRow[1]).toBe(3);
    expect(aRow[2]).toBeCloseTo(13 / 3, 10);
    expect(aRow[3]).toBeCloseTo(1.5275252316519468, 10);
    expect(aRow[4]).toBe(3);
    expect(aRow[5]).toBe(6);

    expect(bRow[0]).toBe("b");
    expect(bRow[1]).toBe(3);
    expect(bRow[2]).toBeCloseTo(5.5, 10);
    expect(bRow[3]).toBeCloseTo(1.0, 10);
    expect(bRow[4]).toBe(4.5);
    expect(bRow[5]).toBe(6.5);
  });

  test("non-numeric variables report N with blank statistics", async () => {
    const outcome = await executeCommand("sum s", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.rows).toEqual([["s", 5, null, null, null, null]]);
  });

  test("date variables report date statistics", async () => {
    const outcome = await executeCommand("sum d ts", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // d: 2026-01-01, 01-02, 01-03, 02-01, 03-01 (one null)
    // day offsets 0,1,2,31,59: mean 18.6 -> 2026-01-19, sd ~26.06 days
    const dRow = block.rows[0];
    expect(dRow[0]).toBe("d");
    expect(dRow[1]).toBe(5);
    expect(dRow[2]).toBe("2026-01-19");
    expect(String(dRow[3])).toMatch(/^26\.06\d* days$/);
    expect(dRow[4]).toBe("2026-01-01");
    expect(dRow[5]).toBe("2026-03-01");
    const tsRow = block.rows[1];
    expect(tsRow[0]).toBe("ts");
    expect(tsRow[1]).toBe(5);
    // times of day pull the mean past the mean of the date parts
    expect(String(tsRow[2])).toMatch(/^2026-01-20 /);
    expect(String(tsRow[4])).toBe("2026-01-01 08:00:00");
    expect(String(tsRow[5])).toBe("2026-03-01 23:59:59");
  });

  test("date filters", async () => {
    const outcome = await executeCommand(
      'sum a if d >= date("2026-02-01")',
      ctx
    );
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // rows 5 (a NULL) and 6 (a=6)
    expect(block.rows[0]).toEqual(["a", 1, 6, null, 6, 6]);
  });

  test("timestamp filters", async () => {
    const outcome = await executeCommand(
      'sum a if ts >= date("2026-01-03 10:00:00")',
      ctx
    );
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // rows 3 (a=3), 5 (a NULL), 6 (a=6)
    expect(block.rows[0][1]).toBe(2);
    expect(block.rows[0][2]).toBeCloseTo(4.5, 10);
  });

  test("string filters with embedded quotes", async () => {
    const outcome = await executeCommand(`sum a if s == "say ""hi"""`, ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.rows[0]).toEqual(["a", 1, 3, null, 3, 3]);
  });

  test("quoted column names", async () => {
    const outcome = await executeCommand(
      "sum `has space` if `select` != 'x'",
      ctx
    );
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // select != 'x' -> rows 3,4,5,6; "has space" in {30,40,50,NULL}
    expect(block.rows[0]).toEqual(["has space", 3, 40, 10, 30, 50]);
  });
});

describe("tabulate", () => {
  test("tab s: frequency, percent, cumulative percent, sorted", async () => {
    const outcome = await executeCommand("tab s", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.sql).toContain("OVER");
    const block = outcome.blocks[0];
    expect(block.kind).toBe("table");
    if (block.kind !== "table") return;
    expect(block.columns).toEqual(["s", "Freq.", "Percent", "Cum."]);
    // non-null values: alpha x2, gamma, it's, say "hi" -- sorted ascending
    expect(block.rows).toEqual([
      ["alpha", 2, "40.00", "40.00"],
      ["gamma", 1, "20.00", "60.00"],
      ["it's", 1, "20.00", "80.00"],
      ['say "hi"', 1, "20.00", "100.00"],
    ]);
  });

  test("tab with filter", async () => {
    const outcome = await executeCommand("tab `select` if c >= 3", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // c >= 3 -> rows 3,4,5,6: select = y,y,y,z
    expect(block.rows).toEqual([
      ["y", 3, "75.00", "75.00"],
      ["z", 1, "25.00", "100.00"],
    ]);
  });

  test("tab on empty result yields empty table (no divide-by-zero)", async () => {
    const outcome = await executeCommand("tab s if c > 99", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.rows).toEqual([]);
  });
});

describe("missing-value syntax", () => {
  const countOf = async (command: string): Promise<string> => {
    const outcome = await executeCommand(command, ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok" || outcome.blocks[0].kind !== "text") {
      return "";
    }
    return outcome.blocks[0].text;
  };

  test("dot literal maps to null semantics", async () => {
    expect(await countOf("count if a == .")).toBe("1");
    expect(await countOf("count if a != .")).toBe("5");
    // Stata idioms: < . is non-missing, >= . is missing
    expect(await countOf("count if a < .")).toBe("5");
    expect(await countOf("count if a >= .")).toBe("1");
  });

  test('empty string matches null (Stata string missing)', async () => {
    expect(await countOf('count if s == ""')).toBe("1");
    expect(await countOf('count if s != ""')).toBe("5");
  });
});

describe("codebook", () => {
  test("codebook a s: type, N, missing, distinct, min/max or top values", async () => {
    const outcome = await executeCommand("codebook a s", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.blocks.length).toBe(2);

    const aBlock = outcome.blocks[0];
    expect(aBlock.kind).toBe("codebookVar");
    if (aBlock.kind !== "codebookVar") return;
    expect(aBlock).toMatchObject({
      variable: "a",
      sqlType: "INTEGER",
      n: 5,
      missing: 1,
      distinct: 5,
      min: "1",
      max: "6",
    });

    const sBlock = outcome.blocks[1];
    if (sBlock.kind !== "codebookVar") return;
    expect(sBlock).toMatchObject({
      variable: "s",
      sqlType: "VARCHAR",
      n: 5,
      missing: 1,
      distinct: 4,
    });
    // top values: alpha (2), then singletons tie-broken by value asc
    expect(sBlock.topValues).toEqual([
      { value: "alpha", freq: 2 },
      { value: "gamma", freq: 1 },
      { value: "it's", freq: 1 },
      { value: 'say "hi"', freq: 1 },
    ]);
  });

  test("codebook date column reports min/max", async () => {
    const outcome = await executeCommand("codebook d", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "codebookVar") return;
    expect(block).toMatchObject({
      variable: "d",
      sqlType: "DATE",
      n: 5,
      missing: 1,
      distinct: 5,
      min: "2026-01-01",
      max: "2026-03-01",
    });
  });

  test("codebook quoted column", async () => {
    const outcome = await executeCommand('codebook `quote"name`', ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "codebookVar") return;
    expect(block.n).toBe(5);
    expect(block.missing).toBe(1);
    expect(block.distinct).toBe(3);
    expect(block.topValues).toEqual([
      { value: "q1", freq: 2 },
      { value: "q2", freq: 2 },
      { value: "q3", freq: 1 },
    ]);
  });
});

describe("browse", () => {
  test("bro a b if c > 2 applies projection and filter to the grid", async () => {
    const outcome = await executeCommand("bro a b if c > 2", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(lastGrid).not.toBeNull();
    expect(lastGrid!.displayColumns).toEqual(["a", "b"]);
    expect(lastGrid!.gridFilterExp).not.toBeNull();
    expect(outcome.sql.length).toBeGreaterThan(0);

    // evaluating the equivalent query yields the filtered, projected rows
    const query = ctx.baseQuery
      .filter(lastGrid!.gridFilterExp as FilterExp)
      .project(lastGrid!.displayColumns!);
    const res = await dbds.evalQuery(query);
    expect(res.schema.columns).toEqual(["a", "b"]);
    expect(res.rowData).toEqual([
      { a: 3, b: null },
      { a: 4, b: 4.5 },
      { a: null, b: 5.5 },
      { a: 6, b: 6.5 },
    ]);
  });

  test("browse SQL executes and respects quoting", async () => {
    const outcome = await executeCommand(
      'bro `has space` `select` if `quote"name` == "q2"',
      ctx
    );
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const res = await dbds.runReadOnlySql(outcome.sql);
    expect(res.schema.columns).toEqual(["has space", "select"]);
    expect(res.rows).toEqual([
      { "has space": 30, select: "y" },
      { "has space": 50, select: "y" },
    ]);
  });
});

describe("count, list, describe, ds", () => {
  test("count with and without filters", async () => {
    const all = await executeCommand("count", ctx);
    expect(all.status).toBe("ok");
    if (all.status !== "ok") return;
    expect(all.blocks[0]).toEqual({ kind: "text", text: "6" });

    const filtered = await executeCommand("count if c > 2", ctx);
    if (filtered.status !== "ok") return;
    expect(filtered.blocks[0]).toEqual({ kind: "text", text: "4" });
  });

  test("list returns capped rows with obs numbers and dots for null", async () => {
    const outcome = await executeCommand("list a s if c >= 5", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.columns).toEqual(["#", "a", "s"]);
    // deterministic order: no grid sort key set, so list falls back to
    // ordering by its own listed columns (a ascending, nulls last)
    expect(block.rows).toEqual([
      [1, 6, "alpha"],
      [2, ".", "gamma"],
    ]);
  });

  test("describe reports observations and types", async () => {
    const outcome = await executeCommand("des a s d", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.blocks[0]).toEqual({
      kind: "text",
      text: "Observations: 6 — Variables: 3",
    });
    const table = outcome.blocks[1];
    if (table.kind !== "table") return;
    expect(table.rows).toEqual([
      ["a", "INTEGER"],
      ["s", "VARCHAR"],
      ["d", "DATE"],
    ]);
  });

  test("ds lists matching names without SQL", async () => {
    const outcome = await executeCommand("ds q*", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.blocks[0]).toEqual({ kind: "text", text: 'quote"name' });
    expect(outcome.sql).toBe("");
  });
});

describe("tab , missing", () => {
  test("includes nulls as '.' sorted last", async () => {
    const outcome = await executeCommand("tab s, missing", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.rows.map((r) => r[0])).toEqual([
      "alpha",
      "gamma",
      "it's",
      'say "hi"',
      ".",
    ]);
    expect(block.rows.map((r) => r[1])).toEqual([2, 1, 1, 1, 1]);
    expect(block.rows[4][3]).toBe("100.00");
    expect(block.rows[0][2]).toBe((100 * (2 / 6)).toFixed(2));
  });
});

describe("grid commands against the session", () => {
  test("keep if updates session filter; subsequent sum respects it", async () => {
    const keep = await executeCommand("keep if c > 2", ctx);
    expect(keep.status).toBe("ok");
    expect(lastGrid).not.toBeNull();
    expect(lastGrid!.sessionFilter).toBeDefined();

    // emulate the app applying the session filter to the context
    ctx.sessionFilter = lastGrid!.sessionFilter as Expr;
    const outcome = await executeCommand("sum a", ctx);
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // rows where c > 2: a in {3, 4, NULL, 6}
    expect(block.rows[0][1]).toBe(3);
    expect(block.rows[0][2]).toBeCloseTo(13 / 3, 10);
  });

  test("drop if negates into the session; count confirms", async () => {
    const drop = await executeCommand("drop if c > 2", ctx);
    expect(drop.status).toBe("ok");
    ctx.sessionFilter = lastGrid!.sessionFilter as Expr;
    const outcome = await executeCommand("count", ctx);
    if (outcome.status !== "ok") return;
    // c <= 2 keeps rows 1 and 2 (c=1,2); null c would be dropped too
    expect(outcome.blocks[0]).toEqual({ kind: "text", text: "2" });
  });

  test("successive keep/drop filters accumulate", async () => {
    const keep = await executeCommand("keep if c >= 2", ctx);
    expect(keep.status).toBe("ok");
    ctx.sessionFilter = lastGrid!.sessionFilter as Expr;

    const drop = await executeCommand("drop if c >= 5", ctx);
    expect(drop.status).toBe("ok");
    ctx.sessionFilter = lastGrid!.sessionFilter as Expr;

    const outcome = await executeCommand("count", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    // c in {2, 3, 3} after keeping c >= 2 and dropping c >= 5
    expect(outcome.blocks[0]).toEqual({ kind: "text", text: "3" });
    expect(outcome.sql).toContain('"c" >= 2');
    expect(outcome.sql).toContain('"c" < 5');
  });

  test("keep varlist narrows subsequent all-variable expansion", async () => {
    const keep = await executeCommand("keep a b c", ctx);
    expect(keep.status).toBe("ok");
    expect(lastGrid!.displayColumns).toEqual(["a", "b", "c"]);

    // emulate the app: session schema now only has a, b, c
    const cmMap: { [c: string]: any } = {};
    for (const colId of ["a", "b", "c"]) {
      cmMap[colId] = fullSchema.columnMetadata[colId];
    }
    ctx.schema = new reltab.Schema(DuckDBDialect, ["a", "b", "c"], cmMap);

    const outcome = await executeCommand("sum", ctx);
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.rows.map((r) => r[0])).toEqual(["a", "b", "c"]);
  });

  test("sort and gsort emit ORDER BY and sort keys", async () => {
    const outcome = await executeCommand("gsort -c a", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(lastGrid!.sortKey).toEqual([
      ["c", false],
      ["a", true],
    ]);
    expect(outcome.sql).toContain("ORDER BY");
    const res = await dbds.runReadOnlySql(outcome.sql);
    expect(res.rows[0].c).toBe(5);
  });

  test("order rearranges display columns", async () => {
    const outcome = await executeCommand("order s d", ctx);
    expect(outcome.status).toBe("ok");
    expect(lastGrid!.displayColumns!.slice(0, 2)).toEqual(["s", "d"]);
  });
});

describe("summarize, detail", () => {
  test("Stata-definition percentiles, moments, and extremes", async () => {
    const outcome = await executeCommand("sum a, d", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    expect(block.kind).toBe("sumDetail");
    if (block.kind !== "sumDetail") return;

    // a: non-null values {1, 2, 3, 4, 6}, N = 5
    expect(block.variable).toBe("a");
    expect(block.n).toBe(5);
    expect(block.sum).toBe(16);
    expect(block.mean).toBeCloseTo(3.2, 12);
    expect(block.sd).toBeCloseTo(Math.sqrt(3.7), 12);
    expect(block.variance).toBeCloseTo(3.7, 12);
    // Stata population moments: m2 = 2.96, m3 = 2.016, m4 = 17.4752
    expect(block.skewness).toBeCloseTo(2.016 / Math.pow(2.96, 1.5), 12);
    expect(block.kurtosis).toBeCloseTo(17.4752 / (2.96 * 2.96), 12);

    const pct = new Map(block.percentiles.map((pe) => [pe.p, pe.value]));
    expect(pct.get(50)).toBe(3); // h = 2.5 -> x_3
    expect(pct.get(25)).toBe(2); // h = 1.25 -> x_2
    expect(pct.get(75)).toBe(4); // h = 3.75 -> x_4
    expect(pct.get(10)).toBe(1);
    expect(pct.get(90)).toBe(6);
    expect(pct.get(1)).toBe(1);
    expect(pct.get(99)).toBe(6);

    expect(block.smallest).toEqual([1, 2, 3, 4]);
    expect(block.largest).toEqual([2, 3, 4, 6]);
    expect(outcome.sql).toContain("quantile_disc");
  });

  test("detail handles multiple variables on one connection", async () => {
    const outcome = await executeCommand("sum a b, detail", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.blocks.map((block) => block.kind)).toEqual([
      "sumDetail",
      "sumDetail",
    ]);
    expect(
      outcome.blocks.map((block) =>
        block.kind === "sumDetail" ? block.variable : null
      )
    ).toEqual(["a", "b"]);
  });

  test("detail respects filters", async () => {
    const outcome = await executeCommand("sum b if c > 2, d", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "sumDetail") return;
    // b in {4.5, 5.5, 6.5}, N = 3
    expect(block.n).toBe(3);
    expect(block.mean).toBeCloseTo(5.5, 12);
    const pct = new Map(block.percentiles.map((pe) => [pe.p, pe.value]));
    expect(pct.get(50)).toBeCloseTo(5.5, 12); // h = 1.5 -> x_2
  });
});

describe("histogram", () => {
  test("default Stata bin rule and frequencies", async () => {
    const outcome = await executeCommand("hist a", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    expect(block.kind).toBe("histogram");
    if (block.kind !== "histogram") return;
    // N=5 -> bins = round(min(sqrt(5), 10*log10(5))) = 2; width = 2.5
    expect(block.n).toBe(5);
    expect(block.freqs).toEqual([3, 2]); // {1,2,3} and {4,6}
    expect(block.binStart).toBe(1);
    expect(block.binWidth).toBeCloseTo(2.5, 12);
  });

  test("bin(5) override", async () => {
    const outcome = await executeCommand("hist a, bin(5)", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "histogram") return;
    expect(block.freqs).toEqual([1, 1, 1, 1, 1]);
  });

  test("histogram on string column errors", async () => {
    const outcome = await executeCommand("hist s", ctx);
    expect(outcome.status).toBe("error");
    if (outcome.status !== "error") return;
    expect(outcome.error).toContain("numeric variable");
  });
});

describe("Stata 19 cross-validation", () => {
  test("matches Stata summarize, detail, tabulate, and count results", async () => {
    const sum = await executeCommand("sum a", ctx);
    expect(sum.status).toBe("ok");
    if (sum.status !== "ok" || sum.blocks[0].kind !== "table") return;
    const sumRow = sum.blocks[0].rows[0];
    expect(sumRow[0]).toBe(stataReference.summarize.variable);
    expect(sumRow[1]).toBe(stataReference.summarize.n);
    expect(sumRow[2]).toBeCloseTo(stataReference.summarize.mean, 12);
    expect(sumRow[3]).toBeCloseTo(stataReference.summarize.sd, 12);
    expect(sumRow[4]).toBe(stataReference.summarize.min);
    expect(sumRow[5]).toBe(stataReference.summarize.max);

    const detail = await executeCommand("sum a, detail", ctx);
    expect(detail.status).toBe("ok");
    if (detail.status !== "ok" || detail.blocks[0].kind !== "sumDetail") {
      return;
    }
    const detailBlock = detail.blocks[0];
    const detailRef = stataReference.summarizeDetail;
    expect(detailBlock.variable).toBe(detailRef.variable);
    expect(detailBlock.n).toBe(detailRef.n);
    expect(detailBlock.sum).toBeCloseTo(detailRef.sum, 12);
    expect(detailBlock.mean).toBeCloseTo(detailRef.mean, 12);
    expect(detailBlock.sd).toBeCloseTo(detailRef.sd, 12);
    expect(detailBlock.variance).toBeCloseTo(detailRef.variance, 12);
    expect(detailBlock.skewness).toBeCloseTo(detailRef.skewness, 12);
    expect(detailBlock.kurtosis).toBeCloseTo(detailRef.kurtosis, 12);
    const percentiles = new Map(
      detailBlock.percentiles.map(({ p, value }) => [String(p), value])
    );
    for (const [p, value] of Object.entries(detailRef.percentiles)) {
      expect(percentiles.get(p)).toBeCloseTo(value, 12);
    }
    expect(detailBlock.smallest).toEqual(detailRef.smallest);
    expect(detailBlock.largest).toEqual(detailRef.largest);

    const detailFiltered = await executeCommand(
      stataReference.summarizeDetailFiltered.command,
      ctx
    );
    expect(detailFiltered.status).toBe("ok");
    if (
      detailFiltered.status !== "ok" ||
      detailFiltered.blocks[0].kind !== "sumDetail"
    ) {
      return;
    }
    expect(detailFiltered.blocks[0].n).toBe(
      stataReference.summarizeDetailFiltered.n
    );
    const filteredPercentiles = new Map(
      detailFiltered.blocks[0].percentiles.map(({ p, value }) => [
        String(p),
        value,
      ])
    );
    for (const [p, value] of Object.entries(
      stataReference.summarizeDetailFiltered.percentiles
    )) {
      expect(filteredPercentiles.get(p)).toBeCloseTo(value, 12);
    }

    const tab = await executeCommand("tab c", ctx);
    expect(tab.status).toBe("ok");
    if (tab.status !== "ok" || tab.blocks[0].kind !== "table") return;
    expect(tab.blocks[0].rows.length).toBe(stataReference.tabulate.rows.length);
    tab.blocks[0].rows.forEach((row, idx) => {
      const expected = stataReference.tabulate.rows[idx];
      // numeric tab values stay numeric; percents display with 2 decimals
      expect(row[0]).toBe(Number(expected.value));
      expect(row[1]).toBe(expected.freq);
      expect(row[2]).toBe(expected.percent.toFixed(2));
      expect(row[3]).toBe(expected.cum.toFixed(2));
    });

    const countAll = await executeCommand("count", ctx);
    expect(countAll.status).toBe("ok");
    if (countAll.status !== "ok") return;
    expect(countAll.blocks[0]).toEqual({
      kind: "text",
      text: String(stataReference.count.all),
    });
    const countFiltered = await executeCommand("count if c > 2", ctx);
    expect(countFiltered.status).toBe("ok");
    if (countFiltered.status !== "ok") return;
    expect(countFiltered.blocks[0]).toEqual({
      kind: "text",
      text: String(stataReference.count.cGreaterThan2),
    });
  });
});

describe("error outcomes", () => {
  test("parse errors produce error outcome with caret", async () => {
    const outcome = await executeCommand("sum a if c >", ctx);
    expect(outcome.status).toBe("error");
    if (outcome.status !== "error") return;
    expect(outcome.error).toContain("unexpected end of input");
    expect(outcome.error).toContain("^");
  });

  test("unknown variable produces error outcome", async () => {
    const outcome = await executeCommand("sum nope", ctx);
    expect(outcome.status).toBe("error");
    if (outcome.status !== "error") return;
    expect(outcome.error).toContain("unknown variable 'nope'");
  });
});
