/**
 * Integration tests: execute the SQL generated by the command planners
 * against a real DuckDB database holding the acceptance fixture, through
 * the read-only SQL API (DbDataSource.runReadOnlySql) and the command
 * executor. Asserts numeric outputs and ordering, not just shapes.
 */
import * as reltab from "reltab";
import {
  DbDataSource,
  DuckDBDialect,
  FilterExp,
  tableQuery,
} from "reltab";
import "reltab-duckdb"; // side effect: registers the duckdb provider
import * as reltabDuckDB from "reltab-duckdb";
import {
  CommandExecutionContext,
  executeCommand,
} from "../src/stataCommand/executor";

let dbds: DbDataSource;
let ctx: CommandExecutionContext;
let lastBrowse: { columns: string[]; filterExp: FilterExp | null } | null =
  null;

/**
 * The acceptance fixture:
 * - numeric columns a, b, c (a and b contain nulls)
 * - string column s with embedded single/double quotes and a null
 * - columns needing SQL identifier quoting: "has space", "select",
 *   "quote""name"
 * - date column d and timestamp column ts, each with a null
 */
const FIXTURE_DDL = `
CREATE TABLE stata_fixture (
  a INTEGER,
  b DOUBLE,
  c INTEGER,
  s VARCHAR,
  "has space" INTEGER,
  "select" VARCHAR,
  "quote""name" VARCHAR,
  d DATE,
  ts TIMESTAMP
)`;

const FIXTURE_ROWS = `
INSERT INTO stata_fixture VALUES
  (1,    1.5,  1, 'alpha',     10,   'x', 'q1', DATE '2026-01-01', TIMESTAMP '2026-01-01 08:00:00'),
  (2,    2.5,  2, 'it''s',     20,   'x', 'q1', DATE '2026-01-02', TIMESTAMP '2026-01-02 09:30:00'),
  (3,    NULL, 3, 'say "hi"',  30,   'y', 'q2', DATE '2026-01-03', TIMESTAMP '2026-01-03 10:00:00'),
  (4,    4.5,  3, NULL,        40,   'y', NULL, NULL,              NULL),
  (NULL, 5.5,  5, 'gamma',     50,   'y', 'q2', DATE '2026-02-01', TIMESTAMP '2026-02-01 12:15:30'),
  (6,    6.5,  5, 'alpha',     NULL, 'z', 'q3', DATE '2026-03-01', TIMESTAMP '2026-03-01 23:59:59')`;

beforeAll(async () => {
  const conn = await reltab.getConnection({
    providerName: "duckdb",
    resourceId: ":memory:",
  });
  dbds = conn as DbDataSource;
  const driver = dbds.db as reltabDuckDB.DuckDBDriver;
  await driver.runSqlQuery(FIXTURE_DDL);
  await driver.runSqlQuery(FIXTURE_ROWS);

  const schema = await dbds.getTableSchema("stata_fixture");
  ctx = {
    schema,
    dialect: DuckDBDialect,
    baseQuery: tableQuery("stata_fixture"),
    runReadOnlySql: (sql: string) => dbds.runReadOnlySql(sql),
    applyBrowse: (columns, filterExp) => {
      lastBrowse = { columns, filterExp };
    },
  };
});

beforeEach(() => {
  lastBrowse = null;
});

describe("read-only SQL guard", () => {
  test("rejects mutation statements", async () => {
    await expect(
      dbds.runReadOnlySql("DELETE FROM stata_fixture")
    ).rejects.toThrow("only a single read-only SELECT");
    await expect(
      dbds.runReadOnlySql("INSERT INTO stata_fixture VALUES (1)")
    ).rejects.toThrow("only a single read-only SELECT");
    await expect(dbds.runReadOnlySql("PRAGMA database_list")).rejects.toThrow(
      "only a single read-only SELECT"
    );
  });

  test("rejects multiple statements and comments", async () => {
    await expect(
      dbds.runReadOnlySql("SELECT 1; SELECT 2")
    ).rejects.toThrow("only a single SQL statement");
    await expect(
      dbds.runReadOnlySql("SELECT 1 -- sneaky")
    ).rejects.toThrow("comments are not permitted");
  });

  test("allows trailing semicolon and quoted semicolons", async () => {
    const r1 = await dbds.runReadOnlySql("SELECT 1 AS x;");
    expect(r1.rows).toEqual([{ x: 1 }]);
    const r2 = await dbds.runReadOnlySql("SELECT 'a;b' AS x");
    expect(r2.rows).toEqual([{ x: "a;b" }]);
  });

  test("normalizes bigint and returns schema", async () => {
    const r = await dbds.runReadOnlySql(
      "SELECT count(*) AS n FROM stata_fixture"
    );
    expect(r.rows).toEqual([{ n: 6 }]);
    expect(typeof r.rows[0].n).toBe("number");
    expect(r.schema.columns).toEqual(["n"]);
  });
});

describe("summarize", () => {
  test("sum a b if c > 2 returns exact statistics per variable", async () => {
    const outcome = await executeCommand("sum a b if c > 2", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.sql).toContain("stddev_samp");
    const block = outcome.blocks[0];
    expect(block.kind).toBe("table");
    if (block.kind !== "table") return;
    expect(block.columns).toEqual([
      "Variable",
      "N",
      "Mean",
      "Std. dev.",
      "Min",
      "Max",
    ]);
    expect(block.rows.length).toBe(2);

    // rows where c > 2: a in {3, 4, NULL, 6}, b in {NULL, 4.5, 5.5, 6.5}
    const [aRow, bRow] = block.rows;
    expect(aRow[0]).toBe("a");
    expect(aRow[1]).toBe(3);
    expect(aRow[2]).toBeCloseTo(13 / 3, 10);
    expect(aRow[3]).toBeCloseTo(1.5275252316519468, 10);
    expect(aRow[4]).toBe(3);
    expect(aRow[5]).toBe(6);

    expect(bRow[0]).toBe("b");
    expect(bRow[1]).toBe(3);
    expect(bRow[2]).toBeCloseTo(5.5, 10);
    expect(bRow[3]).toBeCloseTo(1.0, 10);
    expect(bRow[4]).toBe(4.5);
    expect(bRow[5]).toBe(6.5);
  });

  test("non-numeric variables report N with blank statistics", async () => {
    const outcome = await executeCommand("sum s", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.rows).toEqual([["s", 5, null, null, null, null]]);
  });

  test("date filters", async () => {
    const outcome = await executeCommand(
      'sum a if d >= date("2026-02-01")',
      ctx
    );
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // rows 5 (a NULL) and 6 (a=6)
    expect(block.rows[0]).toEqual(["a", 1, 6, null, 6, 6]);
  });

  test("timestamp filters", async () => {
    const outcome = await executeCommand(
      'sum a if ts >= date("2026-01-03 10:00:00")',
      ctx
    );
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // rows 3 (a=3), 5 (a NULL), 6 (a=6)
    expect(block.rows[0][1]).toBe(2);
    expect(block.rows[0][2]).toBeCloseTo(4.5, 10);
  });

  test("string filters with embedded quotes", async () => {
    const outcome = await executeCommand(`sum a if s == "say ""hi"""`, ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.rows[0]).toEqual(["a", 1, 3, null, 3, 3]);
  });

  test("quoted column names", async () => {
    const outcome = await executeCommand(
      "sum `has space` if `select` != 'x'",
      ctx
    );
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // select != 'x' -> rows 3,4,5,6; "has space" in {30,40,50,NULL}
    expect(block.rows[0]).toEqual(["has space", 3, 40, 10, 30, 50]);
  });
});

describe("tabulate", () => {
  test("tab s: frequency, percent, cumulative percent, sorted", async () => {
    const outcome = await executeCommand("tab s", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.sql).toContain("OVER");
    const block = outcome.blocks[0];
    expect(block.kind).toBe("table");
    if (block.kind !== "table") return;
    expect(block.columns).toEqual(["s", "Freq.", "Percent", "Cum."]);
    // non-null values: alpha x2, gamma, it's, say "hi" -- sorted ascending
    expect(block.rows).toEqual([
      ["alpha", 2, 40, 40],
      ["gamma", 1, 20, 60],
      ["it's", 1, 20, 80],
      ['say "hi"', 1, 20, 100],
    ]);
  });

  test("tab with filter", async () => {
    const outcome = await executeCommand("tab `select` if c >= 3", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    // c >= 3 -> rows 3,4,5,6: select = y,y,y,z
    expect(block.rows).toEqual([
      ["y", 3, 75, 75],
      ["z", 1, 25, 100],
    ]);
  });

  test("tab on empty result yields empty table (no divide-by-zero)", async () => {
    const outcome = await executeCommand("tab s if c > 99", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "table") return;
    expect(block.rows).toEqual([]);
  });
});

describe("codebook", () => {
  test("codebook a s: type, N, missing, distinct, min/max or top values", async () => {
    const outcome = await executeCommand("codebook a s", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(outcome.blocks.length).toBe(2);

    const aBlock = outcome.blocks[0];
    expect(aBlock.kind).toBe("codebookVar");
    if (aBlock.kind !== "codebookVar") return;
    expect(aBlock).toMatchObject({
      variable: "a",
      sqlType: "INTEGER",
      n: 5,
      missing: 1,
      distinct: 5,
      min: "1",
      max: "6",
    });

    const sBlock = outcome.blocks[1];
    if (sBlock.kind !== "codebookVar") return;
    expect(sBlock).toMatchObject({
      variable: "s",
      sqlType: "VARCHAR",
      n: 5,
      missing: 1,
      distinct: 4,
    });
    // top values: alpha (2), then singletons tie-broken by value asc
    expect(sBlock.topValues).toEqual([
      { value: "alpha", freq: 2 },
      { value: "gamma", freq: 1 },
      { value: "it's", freq: 1 },
      { value: 'say "hi"', freq: 1 },
    ]);
  });

  test("codebook date column reports min/max", async () => {
    const outcome = await executeCommand("codebook d", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "codebookVar") return;
    expect(block).toMatchObject({
      variable: "d",
      sqlType: "DATE",
      n: 5,
      missing: 1,
      distinct: 5,
      min: "2026-01-01",
      max: "2026-03-01",
    });
  });

  test("codebook quoted column", async () => {
    const outcome = await executeCommand('codebook `quote"name`', ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const block = outcome.blocks[0];
    if (block.kind !== "codebookVar") return;
    expect(block.n).toBe(5);
    expect(block.missing).toBe(1);
    expect(block.distinct).toBe(3);
    expect(block.topValues).toEqual([
      { value: "q1", freq: 2 },
      { value: "q2", freq: 2 },
      { value: "q3", freq: 1 },
    ]);
  });
});

describe("browse", () => {
  test("bro a b if c > 2 applies projection and filter to the grid", async () => {
    const outcome = await executeCommand("bro a b if c > 2", ctx);
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    expect(lastBrowse).not.toBeNull();
    expect(lastBrowse!.columns).toEqual(["a", "b"]);
    expect(lastBrowse!.filterExp).not.toBeNull();
    expect(outcome.sql.length).toBeGreaterThan(0);

    // evaluating the equivalent query yields the filtered, projected rows
    const query = ctx.baseQuery
      .filter(lastBrowse!.filterExp!)
      .project(lastBrowse!.columns);
    const res = await dbds.evalQuery(query);
    expect(res.schema.columns).toEqual(["a", "b"]);
    expect(res.rowData).toEqual([
      { a: 3, b: null },
      { a: 4, b: 4.5 },
      { a: null, b: 5.5 },
      { a: 6, b: 6.5 },
    ]);
  });

  test("browse SQL executes and respects quoting", async () => {
    const outcome = await executeCommand(
      'bro `has space` `select` if `quote"name` == "q2"',
      ctx
    );
    expect(outcome.status).toBe("ok");
    if (outcome.status !== "ok") return;
    const res = await dbds.runReadOnlySql(outcome.sql);
    expect(res.schema.columns).toEqual(["has space", "select"]);
    expect(res.rows).toEqual([
      { "has space": 30, select: "y" },
      { "has space": 50, select: "y" },
    ]);
  });
});

describe("error outcomes", () => {
  test("parse errors produce error outcome with caret", async () => {
    const outcome = await executeCommand("sum a if c >", ctx);
    expect(outcome.status).toBe("error");
    if (outcome.status !== "error") return;
    expect(outcome.error).toContain("unexpected end of input");
    expect(outcome.error).toContain("^");
  });

  test("unknown variable produces error outcome", async () => {
    const outcome = await executeCommand("sum nope", ctx);
    expect(outcome.status).toBe("error");
    if (outcome.status !== "error") return;
    expect(outcome.error).toContain("unknown variable 'nope'");
  });
});
